version: '3.7'

services:
  node-server:
    container_name: yearn-finance-container
    image: yearn-finance-image
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=4096
    expose:
      - '80'
    ports:
      - '80:80'
